Improvements to runTest.sh
hyperledger/aries-mobile-test-harness pull request #30
Opened 2022-02-14 18:44 UTC by Vanderscycle

using modern unix commands, I have improved the ux to run tests.

2022-02-15 18:09 UTC, nodlesh reviewed
What is the bifold/availableTests.txt used for?

2022-02-15 18:19 UTC, Vanderscycle commented
Used by fzf to list all available tests to choose from.

2022-02-15 18:57 UTC, nodlesh commented
I don't think we need to maintain another file like that. The tags and tests are already in the feature file. 
There is a bug with the manage script, but you should be able to do `./manage tests` and ./manage tags` to tell you what to run. 
The greps need to be updated in the manage script to do recursive like this. 
```
    ;;
  tags)
      grep -rh --include \*.feature @ aries-mobile-tests/features/* |  tr " " "\n" | sort -u | fmt
    ;;
.
.
.
  tests|scenarios)
      grep -rh --include \*.feature -B 1 Scenario aries-mobile-tests/features/*
    ;;
```
I've got an outstanding PR that when merged I'll fix this grep. I would suggest to use that. 
Let's also not get too wrapped up in this, things are going to change on the manage script side as we move forward and determine needs and wants. If this runTest helps you, then good, but don't make it too complex or add overhead.

2022-02-15 19:07 UTC, nodlesh commented
I've just merged a PR that fixes the `./manage tests` and `./manage tags`.

2022-02-15 22:52 UTC, Vanderscycle commented on runTest.sh
> +  bat .runTest
@nodlesh I don't know how to parse the file to get only the uniques so that I may pass it to runTest()

2022-02-15 22:53 UTC, Vanderscycle commented
I refactored the file and improved the workflow clarity on a different while I was trying to parse the input on ./manage tests

2022-02-17 01:07 UTC, ianco commented
FYI you should rebase to reduce the number of commits in the PR

2022-02-17 01:23 UTC, Vanderscycle commented
Oops, I'll revert that one

2022-02-18 21:23 UTC, nodlesh requested changes
Please remove the availableTests.txt. There will be a lot of tags in the feature files. We don't need another file to keep updated. If you want to pull tags get it from the `./manage tags` command.  Thanks.

2022-02-23 15:11 UTC, closed without merging